name: Main workflow
on: 
  push:
    branches:
      - master
      - main
jobs:
  run:
    name: Running nox
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
        uses: actions/checkout@master

    - name: nox install
        run: nox install

      - name: Nox
        run: nox